from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Payload received by the /chat endpoint."""

    session_id: str = Field(
        ...,
        description=(
            "Conversation/session identifier (for example, a WhatsApp number "
            "or any stable user id)."
        ),
    )
    message: str = Field(
        ...,
        description="User message in natural language.",
    )


class ChatResponse(BaseModel):
    """Payload returned by the /chat endpoint."""

    session_id: str = Field(
        ...,
        description="Conversation/session identifier echoed back.",
    )
    answer: str = Field(
        ...,
        description="Final answer text generated by the agent.",
    )
    used_tool: str = Field(
        ...,
        description="High-level tool selected by the agent "
        "(RAG_QA, STRUCTURED_DATA, COMPOSE, FALLBACK, etc.).",
    )
    tool_details: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata about the tool execution.",
    )
    sources: List[str] = Field(
        default_factory=list,
        description="List of source URLs used to answer.",
    )
    history_size: int = Field(
        ...,
        description="Number of messages currently stored in the "
        "conversation history for this session.",
    )
